services:
  certipulse:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: certipulse_app

    restart: unless-stopped

    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0

    ports:
      - "3000:3000"

    env_file:
      - .env

    volumes:
      - ./prisma:/app/prisma