name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Update Repository
        run: |
          cd /opt/apps/certificateGenrater
          git fetch origin
          git reset --hard origin/main

      - name: Build & Restart
        run: |
          cd /opt/apps/certificateGenrater
          docker compose up -d --build

      - name: Cleanup
        run: |
          docker image prune -f