name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Sync project
        run: |
          rsync -av --delete \
            --exclude=".git" \
            --exclude=".env" \
            ./ /opt/apps/certificateGenrater/

      - name: Build & Restart
        run: |
          cd /opt/apps/certificateGenrater
          docker compose up -d --build

      - name: Cleanup
        run: |
          docker image prune -f